name: build java application
on: 
 push:
  branches:
   - master
jobs: 
  buildJob:
    runs-on: ubuntu-latest 
    steps: 
      - name: Clone the Repo 
        uses: actions/checkout@v5 
      - name: Install Java 17 and maven
        uses: actions/setup-java@v5
        with:
         java-version: '17'
         distribution: 'temurin' 
         cache: maven
      - name: build the code
        run: mvn clean install package
